def build_avatar_emblem_recommendation_row(
    kind: str,
    slot: str,
    tier: str,
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    item_explain: str,
    effects: dict,
    auction: dict,
    need_count: int,
    unit_price,
    target_stat: str,
    buffer_stat_scope: str,
    recommendation_priority: int,
) -> dict:
    return {
        "kind": kind,
        "slot": slot,
        "tier": tier,
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "itemExplain": item_explain,
        "effects": effects,
        "auction": auction,
        "needCount": need_count,
        "unitPrice": unit_price,
        "targetStat": target_stat,
        "bufferStatScope": buffer_stat_scope,
        "recommendationPriority": recommendation_priority,
    }
