def build_oath_transcend_recommendation_row(
    slot: str,
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    current_item_name: str,
    current_rarity: str,
    current_effects: dict,
    target_effects: dict,
    effects: dict,
    expected_gold: int,
    materials: list,
    material_text: str,
    target_rarity: str,
) -> dict:
    return {
        "sourceType": "oathTranscend",
        "kind": "oath_transcend",
        "slot": slot,
        "tier": "서약 초월",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "currentItemName": current_item_name,
        "currentRarity": current_rarity,
        "targetItemName": item_name,
        "targetRarity": target_rarity,
        "itemExplain": f"{current_item_name} -> {item_name}",
        "effects": effects,
        "currentEffects": current_effects,
        "targetEffects": target_effects,
        "auction": {"minUnitPrice": expected_gold},
        "expectedGold": expected_gold,
        "materials": materials,
        "materialText": material_text,
    }
