def build_platinum_emblem_recommendation_row(
    slot: str,
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    item_explain: str,
    effects: dict,
    skill_damage_multiplier,
    auction: dict,
    target_skill: str,
    buffer_skill_stat_deltas: dict,
    buffer_skill_levels: dict,
    current_platinum_skill: str,
    buffer_buff_skill_level_delta: int,
    buffer_awakening_skill_level_delta: int,
    missing_slots: list,
    price_source,
    price_warning_text,
    buffer_stat_scope: str,
) -> dict:
    return {
        "kind": "platinumEmblem",
        "slot": slot,
        "tier": "플래티넘",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "itemExplain": item_explain,
        "effects": effects,
        "skillDamageMultiplier": skill_damage_multiplier,
        "auction": auction,
        "needCount": 1,
        "targetSkill": target_skill,
        "bufferSkillStatDeltas": buffer_skill_stat_deltas,
        "bufferSkillLevels": buffer_skill_levels,
        "currentPlatinumSkill": current_platinum_skill,
        "bufferBuffSkillLevelDelta": buffer_buff_skill_level_delta,
        "bufferAwakeningSkillLevelDelta": buffer_awakening_skill_level_delta,
        "missingSlots": missing_slots,
        "priceSource": price_source,
        "priceWarningText": price_warning_text,
        "bufferStatScope": buffer_stat_scope,
        "recommendationPriority": 0,
    }
