def build_raid_armor_upgrade_recommendation_row(**values) -> dict:
    current_body = values["current_equipment_body"]
    target_body = values["target_equipment_body"]
    return {
        "sourceType": "raidArmorUpgrade",
        "slot": target_body["slot"],
        "targetSlotId": target_body["slotId"],
        "tier": values["stage_label"],
        "upgradeStageLabel": values["stage_label"],
        "fromStage": values["from_stage"],
        "toStage": values["to_stage"],
        "transitionKey": f"{values['from_stage']}:{values['to_stage']}",
        "requiredCurrentItemId": values["required_current_item_id"],
        "cardTitle": values["stage_label"],
        "cardSubtitle": target_body["slot"],
        "itemId": target_body["itemId"],
        "itemName": target_body["itemName"],
        "itemRarity": target_body["itemRarity"],
        "iconUrl": target_body["iconUrl"],
        "itemExplain": values["item_explain"],
        "effects": values["effects"],
        "currentEffects": current_body["effects"],
        "targetEffects": target_body["effects"],
        "baseEquipmentBody": values["base_equipment_body"],
        "currentEquipmentBody": current_body,
        "targetEquipmentBody": target_body,
        "auction": values["auction"],
        "expectedGold": values["expected_gold"],
        "materials": values["materials"],
        "materialText": values["material_text"],
        "targetItemId": target_body["itemId"],
        "targetItemName": target_body["itemName"],
        "targetItemRarity": target_body["itemRarity"],
        "targetIconUrl": target_body["iconUrl"],
        "targetItemExplain": target_body.get("itemExplain") or "",
        "simulatorSupported": True,
    }
