def build_relic_craft_recommendation_row(**values) -> dict:
    target_body = values["target_equipment_body"]
    current_body = values["current_equipment_body"]
    return {
        "sourceType": values["source_type"],
        "relicCraftMode": values.get("relic_craft_mode") or "craft",
        "slot": values["slot"],
        "targetSlotId": values["target_slot_id"],
        "tier": values["tier"],
        "cardTitle": values["card_title"],
        "cardSubtitle": values["card_subtitle"],
        "itemId": values["item_id"],
        "itemName": values["item_name"],
        "itemRarity": values["item_rarity"],
        "iconUrl": values["icon_url"],
        "itemExplain": values["item_explain"],
        "effects": values["effects"],
        "currentEffects": values["current_effects"],
        "targetEffects": values["target_effects"],
        "currentPrecisionEffects": values.get("current_precision_effects") or {},
        "targetPrecisionEffects": values.get("target_precision_effects") or {},
        "currentEquipmentBody": current_body,
        "targetEquipmentBody": target_body,
        "auction": values["auction"],
        "expectedGold": values["expected_gold"],
        "craftFixedGold": values["craft_fixed_gold"],
        "tuneFixedGoldPerAttempt": values["tune_fixed_gold_per_attempt"],
        "materials": values["materials"],
        "materialText": values["material_text"],
        "priceComplete": True,
        "currentPrecisionPercent": values.get("current_precision_percent") or 0,
        "targetPrecisionPercent": values["precision_percent"],
        "fullPrecisionOperationCount": values.get("full_precision_operation_count") or values["precision_operation_count"],
        "precisionOperationCount": values["precision_operation_count"],
        "currentSlotSetPoint": values["current_slot_set_point"],
        "targetSlotSetPoint": values["target_slot_set_point"],
        "currentEquipmentSetPoint": values["current_equipment_set_point"],
        "targetEquipmentSetPoint": values["target_equipment_set_point"],
        "minimumCurrentEquipmentSetPoint": values["minimum_current_equipment_set_point"],
        # Compatibility aliases are derived from the normalized bodies only.
        "currentItemId": current_body["itemId"],
        "currentItemName": current_body["itemName"],
        "currentItemRarity": current_body["itemRarity"],
        "currentItemReinforceSkill": current_body.get("itemReinforceSkill") or [],
        "currentItemBuff": current_body.get("itemBuff") or {},
        "targetItemId": target_body["itemId"],
        "targetItemName": target_body["itemName"],
        "targetItemRarity": target_body["itemRarity"],
        "targetIconUrl": target_body["iconUrl"],
        "targetItemExplain": target_body.get("itemExplain") or "",
        "targetItemSetPoint": target_body["tuneSetPoint"],
        "simulatorSupported": True,
    }
