def build_switching_title_recommendation_row(
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    fame,
    auction: dict,
    skill_damage_multiplier: float,
    raw_skill_damage_multiplier: float,
    damage_application_ratio: float,
    damage_application_note: str,
    item_explain: str,
    buff_skill_name: str,
    required_level: int,
    title_skill_level_delta: int,
    enchant_buff_skill_level_delta: int,
    current_title_contribution: int,
    candidate_title_contribution: int,
    current_switching_multiplier: float,
    candidate_switching_multiplier: float,
    source_title_kind: str,
    source_title_name: str,
    purchase_route_label: str,
) -> dict:
    return {
        "kind": "switchingTitle",
        "slot": "벞강 칭호",
        "tier": "버프강화",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "fame": fame,
        "auction": auction,
        "effects": {"skillDamageMultiplier": skill_damage_multiplier},
        "skillDamageMultiplier": skill_damage_multiplier,
        "rawSkillDamageMultiplier": raw_skill_damage_multiplier,
        "damageApplicationRatio": damage_application_ratio,
        "damageApplicationNote": damage_application_note,
        "itemExplain": item_explain,
        "buffSkillName": buff_skill_name,
        "requiredLevel": required_level,
        "titleSkillLevelDelta": title_skill_level_delta,
        "enchantBuffSkillLevelDelta": enchant_buff_skill_level_delta,
        "currentTitleContribution": current_title_contribution,
        "candidateTitleContribution": candidate_title_contribution,
        "currentSwitchingMultiplier": current_switching_multiplier,
        "candidateSwitchingMultiplier": candidate_switching_multiplier,
        "sourceTitleKind": source_title_kind,
        "sourceTitleName": source_title_name,
        "purchaseRoute": "attachedSwitchingTitle",
        "purchaseRouteLabel": purchase_route_label,
    }
