def build_switching_creature_recommendation_row(
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    fame,
    auction: dict,
    skill_damage_multiplier: float,
    raw_skill_damage_multiplier: float,
    damage_application_note: str,
    item_explain: str,
    buff_skill_name: str,
    required_level: int,
    current_creature_contribution: int,
    candidate_creature_contribution: int,
    current_switching_multiplier: float,
    candidate_switching_multiplier: float,
    source_creature_name: str,
    target_creature_name: str,
    purchase_route: str,
    purchase_route_label: str,
) -> dict:
    return {
        "kind": "switchingCreature",
        "slot": "벞강 크리쳐",
        "tier": "버프강화",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "fame": fame,
        "auction": auction,
        "effects": {"skillDamageMultiplier": skill_damage_multiplier},
        "skillDamageMultiplier": skill_damage_multiplier,
        "rawSkillDamageMultiplier": raw_skill_damage_multiplier,
        "damageApplicationNote": damage_application_note,
        "itemExplain": item_explain,
        "buffSkillName": buff_skill_name,
        "requiredLevel": required_level,
        "currentCreatureContribution": current_creature_contribution,
        "candidateCreatureContribution": candidate_creature_contribution,
        "currentSwitchingMultiplier": current_switching_multiplier,
        "candidateSwitchingMultiplier": candidate_switching_multiplier,
        "sourceCreatureName": source_creature_name,
        "targetCreatureName": target_creature_name,
        "purchaseRoute": purchase_route,
        "purchaseRouteLabel": purchase_route_label,
    }
