def build_switching_fragment_recommendation_row(
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    fame,
    auction: dict,
    skill_damage_multiplier: float,
    raw_skill_damage_multiplier: float,
    damage_application_note: str,
    item_explain: str,
    buff_skill_name: str,
    switching_slot: str,
) -> dict:
    return {
        "kind": "switchingFragment",
        "slot": "짙편린",
        "tier": "버프강화",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "fame": fame,
        "auction": auction,
        "effects": {"skillDamageMultiplier": skill_damage_multiplier},
        "skillDamageMultiplier": skill_damage_multiplier,
        "rawSkillDamageMultiplier": raw_skill_damage_multiplier,
        "damageApplicationNote": damage_application_note,
        "itemExplain": item_explain,
        "buffSkillName": buff_skill_name,
        "switchingSlot": switching_slot,
        "purchaseRouteLabel": "",
    }
