def build_switching_platinum_recommendation_row(
    slot: str,
    item_id: str,
    item_name: str,
    item_rarity: str,
    icon_url: str,
    item_explain: str,
    skill_damage_multiplier: float,
    raw_skill_damage_multiplier: float,
    damage_application_note: str,
    auction: dict,
    target_skill: str,
    equivalent_target_skills: list,
    current_platinum_skill: str,
    current_switching_multiplier: float,
    candidate_switching_multiplier: float,
    price_source,
    price_warning_text,
) -> dict:
    target_slot_id = "JACKET" if "상의" in str(slot or "") else "PANTS"
    return {
        "kind": "switchingPlatinumEmblem",
        "slot": slot,
        "tier": "버프강화",
        "itemId": item_id,
        "itemName": item_name,
        "itemRarity": item_rarity,
        "iconUrl": icon_url,
        "itemExplain": item_explain,
        "effects": {"skillDamageMultiplier": skill_damage_multiplier},
        "skillDamageMultiplier": skill_damage_multiplier,
        "rawSkillDamageMultiplier": raw_skill_damage_multiplier,
        "damageApplicationNote": damage_application_note,
        "auction": auction,
        "needCount": 1,
        "targetSkill": target_skill,
        "targetBuffSlot": target_slot_id,
        "targetBuffChanges": {
            "platinumEmblem": {
                "slotId": target_slot_id,
                "itemId": item_id,
                "itemName": item_name,
                "itemRarity": item_rarity,
                "iconUrl": icon_url,
                "targetSkill": target_skill,
                "skillLevel": 1,
            },
        },
        "equivalentTargetSkills": equivalent_target_skills,
        "currentPlatinumSkill": current_platinum_skill,
        "currentSwitchingMultiplier": current_switching_multiplier,
        "candidateSwitchingMultiplier": candidate_switching_multiplier,
        "priceSource": price_source,
        "priceWarningText": price_warning_text,
        "recommendationPriority": 0,
    }
