// 도구 화면에서 사용하는 DOM 참조를 한 곳에 모은다.
export function createToolDomRefs() {
  const $id = (id) => document.getElementById(id);
  const $all = (selector) => Array.from(document.querySelectorAll(selector));


  // DOM references are grouped by screen so later UI changes have one lookup point.
  return {
      // Shared controls
      landingPage: $id('landingPage'),
      toolShell: $id('toolShell'),
      landingServerIdInput: $id('landingServerIdInput'),
      landingCharacterNameInput: $id('landingCharacterNameInput'),
      landingSearchButton: $id('landingSearchButton'),
      landingSearchStatus: $id('landingSearchStatus'),
      landingRecentSearches: $id('landingRecentSearches'),
      landingRecentSearchList: $id('landingRecentSearchList'),
      landingNoticeList: $id('landingNoticeList'),
      resultRecentSearches: $id('resultRecentSearches'),
      resultRecentSearchList: $id('resultRecentSearchList'),
      siteLogoHomeButton: $id('siteLogoHomeButton'),
      feedbackEmailCopyButton: $id('feedbackEmailCopyButton'),
      feedbackEmailCopyStatus: $id('feedbackEmailCopyStatus'),
      devModeToggle: $id('devModeToggle'),
      hellTabButton: $id('hellTabButton'),
      supplyTabButton: $id('supplyTabButton'),
      enchantTabButton: $id('enchantTabButton'),
      tabButtons: $all('.tab-button[data-tab-target]'),

      // Hell calculator inputs
      percentileRange: $id('percentileRange'),
      percentileNumber: $id('percentileNumber'),
      percentileLabel: $id('percentileLabel'),
      percentileSectionLabel: $id('percentileSectionLabel'),
      percentileNumberLabel: $id('percentileNumberLabel'),
      setCount: $id('setCount'),
      epicRate: $id('epicRate'),
      taechoRate: $id('taechoRate'),
      hellPerRun: $id('hellPerRun'),
      recoveryAmount: $id('recoveryAmount'),
      applySupplyHellCalcButton: $id('applySupplyHellCalcButton'),
      supplyHellCalcMeta: $id('supplyHellCalcMeta'),
      epicCraftCost: $id('epicCraftCost'),
      taechoCraftCost: $id('taechoCraftCost'),
      trials: $id('trials'),
      selectedCharacter: $id('selectedCharacter'),
      serverIdInput: $id('serverIdInput'),
      characterNameInput: $id('characterNameInput'),
      addCharacterButton: $id('addCharacterButton'),
      refreshCharactersButton: $id('refreshCharactersButton'),
      clearCharactersButton: $id('clearCharactersButton'),
      searchStatus: $id('searchStatus'),
      charactersJson: $id('charactersJson'),
      error: $id('error'),

      // Hell calculator output
      totalCharacters: $id('totalCharacters'),
      selectedPercentileCard: $id('selectedPercentileCard'),
      selectedPercentileCardLabel: $id('selectedPercentileCardLabel'),
      calcState: $id('calcState'),
      calcMeta: $id('calcMeta'),
      calcMetaDev: $id('calcMetaDev'),
      overviewSummary: $id('overviewSummary'),
      overviewTableBody: $id('overviewTableBody'),
      detailTitle: $id('detailTitle'),
      detailSummary: $id('detailSummary'),
      detailBadge: $id('detailBadge'),
      selectedHellCost: $id('selectedHellCost'),
      selectedHellRuns: $id('selectedHellRuns'),
      craftCost: $id('craftCost'),
      craftRoute: $id('craftRoute'),
      verdictText: $id('verdictText'),
      verdictSub: $id('verdictSub'),
      quantileCompact: $id('quantileCompact'),
      p50Cost: $id('p50Cost'),
      p50Runs: $id('p50Runs'),
      p66Cost: $id('p66Cost'),
      p66Runs: $id('p66Runs'),
      p80Cost: $id('p80Cost'),
      p80Runs: $id('p80Runs'),
      meanCost: $id('meanCost'),
      meanRuns: $id('meanRuns'),
      setTableBody: $id('setTableBody'),
      sortButtons: $all('.sort-button[data-sort-key]'),

      // Enchant price table
      enchantServerIdInput: $id('enchantServerIdInput'),
      enchantCharacterNameInput: $id('enchantCharacterNameInput'),
      loadEnchantCharacterButton: $id('loadEnchantCharacterButton'),
      enchantCharacterPortrait: $id('enchantCharacterPortrait'),
      enchantCharacterStatus: $id('enchantCharacterStatus'),
      enchantSlotFilter: $id('enchantSlotFilter'),
      enchantTierFilter: $id('enchantTierFilter'),
      enchantIncludeControls: $id('enchantIncludeControls'),
      enchantTitleBeadOnlyToggle: $id('enchantTitleBeadOnlyToggle'),
      enchantMaterialCostToggle: $id('enchantMaterialCostToggle'),
      safeAmplificationModeSelect: $id('safeAmplificationModeSelect'),
      refreshEnchantCardsButton: $id('refreshEnchantCardsButton'),
      enchantStatus: $id('enchantStatus'),
      enchantEfficiencyLegend: $id('enchantEfficiencyLegend'),
      enchantRecommendList: $id('enchantRecommendList'),
      enchantTableBody: $id('enchantTableBody'),

      // Revelation management inputs
      supplyServerIdInput: $id('supplyServerIdInput'),
      supplyCharacterNameInput: $id('supplyCharacterNameInput'),
      addSupplyCharacterButton: $id('addSupplyCharacterButton'),
      refreshSupplyCharactersButton: $id('refreshSupplyCharactersButton'),
      resetSupplySelectionsButton: $id('resetSupplySelectionsButton'),
      enableAllSupplyHellsButton: $id('enableAllSupplyHellsButton'),
      disableAllSupplyHellsButton: $id('disableAllSupplyHellsButton'),
      clearSupplyCharactersButton: $id('clearSupplyCharactersButton'),
      moveSupplyToHellButton: $id('moveSupplyToHellButton'),
      moveSupplyToAltButton: $id('moveSupplyToAltButton'),
      supplyPresetButtons: $all('[data-supply-preset]'),

      // Revelation management output
      supplySearchStatus: $id('supplySearchStatus'),
      supplyError: $id('supplyError'),
      supplyTotalUsage: $id('supplyTotalUsage'),
      supplyTotalResetUsage: $id('supplyTotalResetUsage'),
      supplyTotalSoul: $id('supplyTotalSoul'),
      supplyTotalSoulSub: $id('supplyTotalSoulSub'),
      supplySoulExcludeControls: $id('supplySoulExcludeControls'),
      supplyTotalEvent: $id('supplyTotalEvent'),
      supplyTotalEventSub: $id('supplyTotalEventSub'),
      supplyTotalTodayUsage: $id('supplyTotalTodayUsage'),
      supplyTotalBound: $id('supplyTotalBound'),
      supplyTotalAccount: $id('supplyTotalAccount'),
      supplyTotalAccountSub: $id('supplyTotalAccountSub'),
      supplyHellRosterList: $id('supplyHellRosterList'),
      supplyAltRosterList: $id('supplyAltRosterList'),
      supplyHellRosterCount: $id('supplyHellRosterCount'),
      supplyAltRosterCount: $id('supplyAltRosterCount'),
      supplyDetailTitle: $id('supplyDetailTitle'),
      supplyDetailUsage: $id('supplyDetailUsage'),
      supplyDetailUsageSub: $id('supplyDetailUsageSub'),
      supplyDetailTodayNeed: $id('supplyDetailTodayNeed'),
      supplyDetailTodayNeedSub: $id('supplyDetailTodayNeedSub'),
      supplyDetailTodayHell: $id('supplyDetailTodayHell'),
      supplyDetailTodayHellSub: $id('supplyDetailTodayHellSub'),
      supplyDetailBound: $id('supplyDetailBound'),
      supplyDetailBoundSub: $id('supplyDetailBoundSub'),
      supplyDetailRecovery: $id('supplyDetailRecovery'),
      supplyDetailRecoverySub: $id('supplyDetailRecoverySub'),
      supplyDetailAccount: $id('supplyDetailAccount'),
      supplyDetailHell: $id('supplyDetailHell'),
      supplyDetailHellSub: $id('supplyDetailHellSub'),
      supplyDetailEditor: $id('supplyDetailEditor'),
      supplyDetailTableBody: $id('supplyDetailTableBody'),
      supplyReferenceTableBody: $id('supplyReferenceTableBody'),
      supplyContentControls: $id('supplyContentControls'),
    };
}
